### ISSUE TITLE
Getting 'Bad Credentials' when trying to use this step

### ISSUE THREAD

**Issue by mvrdrew** [kvvzr/bitrise-step-comment-on-github-pull-request#10]
I've created a Personal Access Token with the repo(Full control of private repositories) scope and I'm using this for my credentials. However, when I try to run this step it continually gives me a 'Bad Credentials' error.

```
Config:
- AuthToken: [REDACTED]
- Body: Testing adding a comment to a pull request from Bitrise
- RepositoryURL: [REDACTED]
- IssueNumber: 360
- APIBaseURL: https://api.github.com
Success: {"message":"Bad credentials","documentation_url":"https://developer.github.com/v3"}
```

I can't find anything I'm doing wrong and I can't find any documentation that suggests what might be going wrong. Any suggestions would be greatly appreciated as I only have so much hair to tear out.

Thanks in advance!

**Comment by kvvzr** [comment]
If it still occurs, please reopen this issue.
