### ISSUE TITLE
GitHub deprecating Basic Auth

### ISSUE THREAD

**Issue by lpusok** [kvvzr/bitrise-step-comment-on-github-pull-request#11]
@kvvzr Please check: https://developer.github.com/changes/2020-02-14-deprecating-password-auth/

Found a reference to Basic Auth in the step: https://github.com/kvvzr/bitrise-step-comment-on-github-pull-request/blob/37a692511ecaa1d369d44b7ce5284d6961258d4d/main.go#L59
Maybe https://github.com/google/go-github could be used for the API operation.

Can you update the step or confirm that it will work after the deprecation?

**Comment by lpusok** [comment]
Based on https://docs.github.com/en/rest/overview/other-authentication-methods#via-oauth-and-personal-access-tokens, tokens will continue to work with Basic Authentication (username/password will be deprecated). Asked GitHub support to confirm.

**Comment by kvvzr** [comment]
Thanks for the information. I fixed it. 🙏
