### ISSUE TITLE
APIBaseURL no longer honored in version 0.10.0

### ISSUE THREAD

**Issue by DamienBitrise** [kvvzr/bitrise-step-comment-on-github-pull-request#16]
APIBaseURL is never used in version 0.10.0

See: https://github.com/kvvzr/bitrise-step-comment-on-github-pull-request/blob/master/main.go#L18 

0.9.4 uses the step input however
https://github.com/kvvzr/bitrise-step-comment-on-github-pull-request/blob/0.9.4/main.go#L42

**Comment by sergiomarqmoura** [comment]
I think this can now be closed, after the release of [0.10.1](https://github.com/kvvzr/bitrise-step-comment-on-github-pull-request/releases/tag/0.10.1)

**Comment by kvvzr** [comment]
[0.10.1](https://github.com/kvvzr/bitrise-step-comment-on-github-pull-request/releases/tag/0.10.1) has been merged into steplib. Thanks for your help!
