### ISSUE TITLE
Is this step still maintained?

### ISSUE THREAD

**Issue by BirmacherAkos** [kvvzr/bitrise-step-comment-on-github-pull-request#17]
Hey @kvvzr 
Akos here from Bitrise.
First of all, I'd like to thank you for all of your hard work with this step and for helping the Bitrise community. 🚀

I'm reaching out to you as we are working on keeping the Bitrise step library up to date by deprecating the [abandoned steps](https://devcenter.bitrise.io/en/steps-and-workflows/developing-your-own-bitrise-step/sharing-steps-with-all-bitrise-users.html#abandoned-steps) that are not maintained anymore.  🧹
We saw some older open issues for your step with no response. 

Could you please let me know your intentions with the step? 
If you don't have time to work on the step, then we may deprecate it from the step library.

**Comment by kvvzr** [comment]
Hi, @BirmacherAkos

I haven't been using GitHub for development recently, so maintenance has been lacking.
I will be responding on the current issue in a few days. I understand that this step is important for developers, so I would like to keep maintaining it.

...Or deprecate this step, could you provide a similar step as an official step?

**Comment by BirmacherAkos** [comment]
@kvvzr this is awesome news 🥳 
No, at the moment we don't offer any similar Bitrise Step, so your Step is a huge help to the Bitrise community. 

_I'm closing this issue, but let me know if you have any questions. 🚀_
