### ISSUE TITLE
Update comment tag section adds dashes 

### ISSUE THREAD

**Issue by RonyBrosh** [kvvzr/bitrise-step-comment-on-github-pull-request#19]
First of all, Thanks, your step is really great!

When adding a tag for the `Update comment tag` section the tag is posted with leading and trailing double dashes.
For example, if my tag is MY TAG, it will be posted on Github as **--**MY TAG**--**

I found this code snippet in your codebase:
// wraps the tag in some special characters to avoid colliding with random text
func decoratedTag(tag string) string {
	return fmt.Sprintf("-- %s --", tag)
}

It will be great if those dashes will not be there so we could **hide** the tag using  or instead just add the angle brackets to hide the tag.
Cheers!

**Comment by RonyBrosh** [comment]
This is the body

**Comment by RonyBrosh** [comment]
TEST_BODY

**Comment by kvvzr** [comment]
merged https://github.com/kvvzr/bitrise-step-comment-on-github-pull-request/pull/20
