### ISSUE TITLE
"message: Not Found" Error

### ISSUE THREAD

**Issue by haikov** [kvvzr/bitrise-step-comment-on-github-pull-request#5]
Hi @kvvzr! First of all, thank you for such a great plugin, we've found it very useful!

But we're getting an error when trying to send a comment.

In the step's log I see the following message:
```
"Success: {"message":"Not Found","documentation_url":"https://developer.github.com/v3/issues/comments/#create-a-comment"}"
```

### Steps to reproduce

1. Add "Comment on PR" step on Bitrise.
2. Generate a token at `https://github.com/settings/tokens` with scope `repo:status`
3. Add the token to the step.
4. Add message body as following: `Android build is Ready! Get it at Bitrise: $BITRISE_PUBLIC_INSTALL_PAGE_URL`

### Build Log
![image](https://user-images.githubusercontent.com/9068073/49376666-07172300-f719-11e8-8070-5955137303cc.png)

Do you have any thought on it?

Thanks!

**Comment by kvvzr** [comment]
Thank you for using!

Is the value of `GitHub PullRequest or Issue number` set to `$BITRISE_PULL_REQUEST` ?
Please make sure that number 23 PullRequest exists on your repository.

And I may be mistakenly writing the document.
Can you turn on the scope of repo (Full control of private repositories) and try again?

Thanks!

**Comment by haikov** [comment]
@kvvzr yep, I created a token with the `repo` scope and then it worked (that was the only thing I changed). Probably it would be great to update the documentation :)

**Comment by cafedeichi** [comment]
@kvvzr 
Hi,
I got the same error today. 
It worked fine on some workflows, but the others didn't unfortunately. 
Seems like the difference among them is only whether they've been already merged or not, though.
Does the step' behavior depend on the status of the PR?
