### ISSUE TITLE
There is no settings to change the GitHub API base url

### ISSUE THREAD

**Issue by SocialSupaCrew** [kvvzr/bitrise-step-comment-on-github-pull-request#7]
Hello @kvvzr, Thanks for your work on this useful step!

I'm trying to use it with a Github Enterprise repository and It doesn't work.

When using Github Enterprise the API base url is not `https://api.github.com` but something like : `https://[host]/api/v3`

It would be nice to be able to set this base url (like in the official "GitHub Status" step) because right now people hosting their Github Enterprise can't use this step!

Do you think it's possible to add this settings ?

**Comment by kvvzr** [comment]
@SocialSupaCrew Thank you for using!
I added a setting to change Base URL. Please wait a while until it is released to Bitrise.

**Comment by SocialSupaCrew** [comment]
Thank you very much for the change!
