### ISSUE TITLE
Add option to comment on a commit

### ISSUE THREAD

**Issue by GrahamBorland** [kvvzr/bitrise-step-comment-on-github-pull-request#9]
Could you consider adding an option to comment on a specific commit?

**Comment by GrahamBorland** [comment]
The commit is available in `$BITRISE_GIT_COMMIT` and we need to post to 
`/repos/owner/repo/commits/$BITRISE_GIT_COMMIT/comments`

**Comment by kvvzr** [comment]
Hi,
I think it is better to use Danger etc. for complex comment operations.
Please describe use cases and reopen it.
